permalink: /blog/:year/:month/:day/:title

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - vendor
  - "*.iml"
  - fetch_yt_preview

highlighter: rouge
markdown: kramdown

external: https://tracking.octoprint.org
#external: http://192.168.1.3:4000
baseurl: ""

title: tracking.octoprint.org
description: Anonymous Usage Tracking in OctoPrint

author:
  name: Gina Häußge
  twitter: foosel

sourcerepo: https://github.com/OctoPrint/OctoPrint
forum: https://community.octoprint.org
discord: https://discord.octoprint.org
irc: ircs://irc.libera.chat:6697/#octoprint

twitter: OctoPrint3D
mastodon: "@octoprint@fosstodon.org"
youtube: OctoPrint3D

twitterlink: https://twitter.com/OctoPrint3D
mastodonlink: https://fosstodon.org/@octoprint
youtubelink: https://www.youtube.com/c/OctoPrint3D
